// Generated by CoffeeScript 1.9.3
(function() {
  var sampleData, song;

  sampleData = [
    {
      src: 'http://datashat.net/music_for_programming_1-datassette.mp3',
      img: 'album/song1.png',
      title: 'Song #1'
    }, {
      src: 'http://datashat.net/music_for_programming_2-sunjammer.mp3',
      img: 'album/song2.png',
      title: 'Song #2'
    }, {
      src: 'http://datashat.net/music_for_programming_3-datassette.mp3',
      img: 'album/song3.png',
      title: 'Song #3'
    }, {
      src: 'http://datashat.net/music_for_programming_4-com_truise.mp3',
      img: 'album/song4.png',
      title: 'Song #4'
    }
  ];

  song = new Song(sampleData);

  song.repeat = true;

  song.shuffle();

  window.onload = function() {
    var makeTag;
    makeTag = function(tag) {
      return document.createElement(tag);
    };
    (function() {
      var nowPlaying, setNowPlaying;
      nowPlaying = document.getElementById('now-playing');
      setNowPlaying = function() {
        var art, title;
        title = makeTag('p');
        title.innerHTML = song.getTitle(song.getSong()) + '<br>';
        art = song.getAlbum(song.getSong());
        nowPlaying.innerHTML = '';
        nowPlaying.appendChild(title);
        return nowPlaying.appendChild(art);
      };
      song.onsongchange = setNowPlaying;
      return setNowPlaying();
    })();
    return (function() {
      var playlist, skipToSong;
      skipToSong = function(songNum) {
        return song.skipTo(songNum);
      };
      playlist = document.getElementById('playlist');
      return song.playlist.forEach(function(tag, index) {
        var div, h2;
        div = makeTag('div');
        div.className = 'playlist';
        h2 = makeTag('h2');
        h2.innerHTML = song.getTitle(tag);
        div.appendChild(h2);
        playlist.appendChild(div);
        return div.addEventListener('click', function() {
          return skipToSong(index);
        });
      });
    })();
  };

}).call(this);
